{
 "title": "MooseFS - metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(mfs_cgi_info,job)" } },
   {
    "name": "cgi_address",
    "query": {
     "query": "label_values(mfs_cgi_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Raw Space Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_info_licence_current_raw_data_usage{job=\"$job\"} / mfs_info_licence_max_raw_data_usage{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster usage",
   "type": "gauge",
   "description": "Total usage of the cluster",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_info_general_total_space{job=\"$job\"} - mfs_info_general_avail_space{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    { "expr": "mfs_info_general_total_space", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Master Server CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_info_masters_cpu_usage_percent{state=\"LEADER\",job=\"$job\"}",
     "legendFormat": "{{ip}} {{state}}"
    }
   ]
  },
  {
   "title": "Master Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mfs_info_masters_misc{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunk Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mfs_chunkservers_misc{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Licence Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "max by(issuer, max_version, expires, type, client) (mfs_info_licence_misc{job=\"$job\"})"
    }
   ]
  },
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Master CPU usage",
   "type": "timeseries",
   "description": "Master Server CPU usage",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mfs_info_general_cpu_user_percent{job=\"$job\"}",
     "legendFormat": "CPU user"
    },
    {
     "expr": "mfs_info_general_cpu_system_percent{job=\"$job\"}",
     "legendFormat": "CPU system"
    }
   ]
  },
  {
   "title": "Available Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mfs_info_general_avail_space{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mfs_info_general_filesystem_objects{job=\"$job\"}",
     "legendFormat": "All objects"
    },
    {
     "expr": "mfs_info_general_files{job=\"$job\"}",
     "legendFormat": "Files"
    },
    {
     "expr": "mfs_info_general_directories{job=\"$job\"}",
     "legendFormat": "Directories"
    }
   ]
  },
  {
   "title": "Followers Metadata Delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "mfs_info_masters_metadata_delay{job=\"$job\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Missing Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_info_fs_loop_missing_files{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Undergoal Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_info_fs_loop_undergoal_files{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Chunks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_info_chunks_summary_regularchunks_missing{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endangered Chunks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_info_chunks_summary_regularchunks_endangered{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Undergoal Chunks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_info_chunks_summary_regularchunks_undergoal{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overgoal Chunks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_info_chunks_summary_regularchunks_overgoal{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chunk Servers HDD Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Chunk Servers Total Space",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_chunkservers_hdd_regular_total{job=\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Chunk Servers Used Space",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_chunkservers_hdd_regular_used_percent{job=\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Operations on cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "mfs_mastercharts_read{job=\"$job\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "mfs_mastercharts_write{job=\"$job\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mfs_mastercharts_mountbytrcvd{job=\"$job\"}",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "mfs_mastercharts_mountbytsent{job=\"$job\"}",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Bytes read and written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mfs_mastercharts_bytesread{job=\"$job\"}",
     "legendFormat": "Bytes read"
    },
    {
     "expr": "mfs_mastercharts_byteswrite{job=\"$job\"}",
     "legendFormat": "Bytes written"
    }
   ]
  },
  {
   "title": "Chunk operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "mfs_mastercharts_delete{job=\"$job\"}",
     "legendFormat": "Chunk deletions"
    },
    {
     "expr": "mfs_mastercharts_replicate{job=\"$job\"}",
     "legendFormat": "Chunk replications"
    }
   ]
  }
 ]
}